version: '3'
services:
  mysql-standalone:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=parking
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    image: app
    ports:
      - 8000:8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/parking
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone